export const PAYMENT_TYPES = ["CASH", "CARD"];
export const DOCTOR_STATUSES = ["AVAILABLE", "NOT_AVAILABLE"];
export const APPOINTMENTS_STATUSES = ["CONFIRMED","CANCELLED"];
export const DIAGNOSIS_TYPES = ["COMPLAINT", "PRIMARY", "MIDDLE", "FINAL", "PRESCRIPTION"];
